### ISSUE TITLE
Track interaction with the tool

### ISSUE THREAD

**Issue by michaelmior** [michaelmior/relational-playground#2]
It's important to understand how students are interacting with the tool. Below are examples of a few things that we may want to log.

* Which datasets are commonly used
* Queries entered
* What types of expressions are clicked on
* What browsing features of tables are used

**Comment by michaelmior** [comment]
Consider taking a look at [custom events](https://developers.google.com/analytics/devguides/collection/analyticsjs/events) with Google Analytics.

**Comment by michaelmior** [comment]
[This library](https://github.com/yahoo/react-i13n) looks useful to check out.

**Comment by ceb3745** [comment]
41 of MultiTable.js - The dropdown menu -> can do specific method for which relation is being used, Doctor vs Patient.

163 of data.js - The re-render method for when a new value is clicked on. Can send through which operation was selected -> Select, Rename, Project, Join etc. 

65 of SqlEditor.js - The sql entered -> sending the statement itself.

**Comment by michaelmior** [comment]
Looks like a good start! When it comes to the SQL entered, I would make use of the existing timeout so the SQL isn't sent on every key press. (Perhaps even a second, longer timeout for this.)
