### ISSUE TITLE
Add support for OR in query conditions

### ISSUE THREAD

**Issue by michaelmior** [michaelmior/relational-playground#65]
Currently only `AND` is supported, but `OR` should be as well. This will require looking at the conditions in the parsed query and deciding on a structure to represent the expression. This structure would then be used to display the relational algebra expression as well as evaluate the query when the expression is selected.

**Comment by michaelmior** [comment]
This actually seems to be already implemented, but needs tests added for the following:

* Conversion of SQL expressions to relational algebra
* Evaluation of these relational algebra expressions
* Visual representation of the expressions

**Comment by axj2613** [comment]
1.  Have test cases for compounds of ANDs and ORs.
2. Have test cases for compounds of ANDs and ORs with parenthesis that give precedence to OR.
3. Have a test file for util.js
4. Check the visual rendering of parenthesis in relational expressions.
